### ISSUE TITLE
No horizontal scrollbar in FileTree. Is it bug?

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#113]
Tested in 2.6.5.

**Comment by kitepad** [comment]
Find out reason: TVS_NOHSCROLL is set in FileTree init method.

**Comment by stefankueng** [comment]
that was done because previously the dark mode didn't draw those scrollbars correctly. But now that we solved that problem, the scrollbar can be shown again.

**Comment by gmcode** [comment]
I'm not convinced the problem is fixed. I am running the version of bowpad with the TVS_NOHSCROLL  flag removed, and the issue still exists.

I am more inclined to think the issue is that the SETREDRAW true/false calls are not paired correctly but I am not sure yet even though I can reproduce the problem every time.
