### ISSUE TITLE
Behavior of Ctrl+Click in editor

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#149]
In many editors, if we press the Ctrl key and then click onto the editor, it will select the whole word. It is very convenient to select a word that way.
But in BowPad, it adds a insertion point instead.

Is it possible to change that behavior to follow other text editors and use another modifier keys to add insertion points? Like Visual Studio, the modifier keys are Ctrl+Alt.

**Comment by stefankueng** [comment]
that's the default behavior of Scintilla.
Also, I can't find an editor that would select the word on Ctrl+click.
And on another not: Ctrl+Alt should *never* be used for shotcuts (at least not default ones) because that's what the "Alt Gr" key on e.g. German keyboards does, and that key is used for German specific keys and stuff.

**Comment by wmjordan** [comment]
Visual Studio, EditPlus are those type of editors.

SublimeText works alike BowPad.

Visua Studio Code has nothing difference with or without Ctrl key.

**Comment by stefankueng** [comment]
in my VS, Ctrl+click goes to the declaration of the clicked variable/method/whatever.
But anyway: changing this in BP would require implementing the whole selection/multi-selection again in BP since Scintilla doesn't allow to configure this.

I think the effort to change this (I don't even want this to change) or make it configurable is too big for the little gain.
Sorry.

**Comment by wmjordan** [comment]
I have configured my VS to use another keyboard modifier to go to definition, thus I can Ctrl+Click to select a word there.

I can understand your consideration. Thank you for your time on explaining this.
