### ISSUE TITLE
Possible to automatically update the File Tree?

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#150]
Is it appropriate to use [ReadDirectoryChangesW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw) to monitor the directories where files are opened and update the File Tree window according to corresponding file system events?

````C
// Setup the ReadDirectoryChangesW
....

// Cache the FILE_NOTIFY_INFORMATION info
....

// Handle the notification
if (info.Action == FILE_ACTION_ADDED) {
   // add a node in the file tree
}
else if (info.Action == FILE_ACTION_REMOVED) {
   // remove the node in the file tree
}
else if (info.Action == FILE_ACTION_RENAMED_OLD_NAME) {
   // rename the node in the file tree, use the entry with FILE_ACTION_RENAMED_NEW_NAME
}
````

There's a [C# version of adopting that Windows API](https://referencesource.microsoft.com/#System/services/io/system/io/FileSystemWatcher.cs,713a8b1d884813dc) to watch file system changes.

**Comment by stefankueng** [comment]
Ok, worst case scenario:

1. create a file "test.txt" on C:\
2. open that file in BP
3. BP shows the tree view, rooting on C:\

even if the system appears to be idle, there are hundreds of notifications for file changes, because the OS itself constantly creates/deletes temp files.
Now, start a rebuild of a bigger c++ project in VS that also sits somewhere on the C drive, and the notifications spike up, making BP to use all CPU in the watcher thread.

the ReadDirectoryChangesW API should only be used to monitor specific folders for changes, e.g. to detect changes that require synching something, but not to monitor whole drives or huge trees.

So I've decided to not implement this.

**Comment by wmjordan** [comment]
That should not be the case.

In the `ReadDirectoryChangesW` function, there's a parameter `bWatchSubtree` which specifies whether sub-directories are monitored.
Furthermore, we shall only monitor those directories are expanded in the File Tree, not those closed. For instance, the `C:\Windows` which is closed in the File Tree should not be monitored.

**Comment by wmjordan** [comment]
We can also take a look at the [C# code which utilize that API](https://referencesource.microsoft.com/#System/services/io/system/io/FileSystemWatcher.cs,729).

The `includeSubdirectories` variable--the aforementioned `bWatchSubtree` parameter in the `ReadDirectoryChangesW` function, is by default `false` (0). I used that API with `bWatchSubtree = 0` monitoring my `C:\` directory. I did not received tremendous event notifications. But when I created or deleted a file in the root directory of C:, my program did received corresponding notifications.

Please try again with `bWatchSubtree = 0` and see whether it works. For instance, the following screenshot was taken on the root of my drive `M:`.

![image](https://user-images.githubusercontent.com/12182730/120052653-e49bc180-c058-11eb-8350-029e6b264582.png)

BowPad should monitor on `M:\` (the File Tree root), `M:\com\` (the expanded folder), with `bWatchSubtree = 0`.
Since `Temp` and `Vivaldi Cache` folders are not expanded, they should not be monitored for changes.
