### ISSUE TITLE
Improve the numeric highlight in log lexer?

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#187]
Nowadays the log lexer highlights SOME (not all) numbers within words.
My log files output many hex-bin representations, some characters got highlighted, some were not.
They do not look good.
![image](https://user-images.githubusercontent.com/12182730/124525550-47d7fb00-de32-11eb-8c67-efa1d53b4e99.png)

Is it appropriated to only highlight numbers that are not mixed with alphabetic characters?

**Comment by stefankueng** [comment]
I can change it so that numbers are only detected if there a non-alphanumeric char before. That means that your hex numbers won't be treated as numbers anymore (also not part of them).
Because detecting hex numbers without e.g. 0x before can't be really done, for example 'babe' would be detected as a number then even though it could be a word...

**Comment by wmjordan** [comment]
Hmm, actually I don't expect hex detection at all. We don't have much BABE, but so frequently we have FACE to deal with.

The update is better now.
