### ISSUE TITLE
Program hangs when trying to open BowPad from the context menu

### ISSUE THREAD

**Issue by neeo01** [stefankueng/BowPad#188]
In Windows 10 X64 BowPad 2.7.1 hangs when opening a text file from the context, right-click menu "Edit with BowPad". The program must be forcibly closed. This happens with 32-bit and 64-bit versions and also goes back a few versions. BowPad 2.5.2 on another computer does not fail this way.

**Comment by stefankueng** [comment]
but starting BP and opening the file then works?
what happens if you open the file by double-clicking on it in explorer?
does it also hang if you right-click on the file in explorer, then select "open with" and then select BP to open the file with?

If you're not using the Windows virus scanner but another product, it could be that this product is interfering - try adding BP as a trusted exe and see if that helps.

**Comment by stefankueng** [comment]
two months without a response, closing the issue now.
