### ISSUE TITLE
Inconsistent Spelling Squiggle

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#208]
The attached gif demonstrates what seems an inconsistency of the spelling squiggle Kind Regards

![inconsistent spelling squiggle](https://user-images.githubusercontent.com/48535920/135047608-bb34a76e-51d2-40b1-acbd-5e9008f98ad6.gif)

**Comment by stefankueng** [comment]
well, yes. The squiggles can not be 100% correct while you're typing because then words are not complete yet. And it takes a few ms when the check runs until the squiggles appear.
Your animation shows that the squiggles are correct a few ms after you stop typing.
Ok we could make this go away by doing the spell check immediately after ever char entered, but that would slow down BP a lot.
