### ISSUE TITLE
Feature request: Add "Replace All In Folder" like “Find All In Folder”

### ISSUE THREAD

**Issue by AndyLuke** [stefankueng/BowPad#224]
Hello, thank you very much for a good notepad program under a free open source license!

It would be useful to Add "Replace All In Folder" like “Find All In Folder”, otherwise if I want to replace some content for all files, I must use "Find All In Folder" to find all the target files and open all, then use "Replace All In All Tabs" to replace them.

**Comment by stefankueng** [comment]
it's dangerous to "replace all in folder" because there's no undo if the file is not open in BP.
Opening all files in the folder might also not be a good idea depending on how many files are in the folder.
And first searching, then opening and then replacing strings will take too long.

I recommend using grepWin for tasks like this, after all I wrote it exactly for that:
https://tools.stefankueng.com/grepWin.html
https://github.com/stefankueng/grepWin
