### ISSUE TITLE
How to explicitly enable the Save button via script?

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#231]
Previously I have written a plugin script which extracts lines containing selected text.
In the script, it creates a new document, put the lines into it, then cleared the dirty flag preventing BowPad from asking to save that document when it is closed.
However, the Save button is also disabled after that. To save the document, we have to use the Save As command, which is not so convenient.
Can I explicitly enable the Save button via script?

**Comment by stefankueng** [comment]
Sorry, but that's not possible since the save button is not controlled by your plugin but by its own command. Each command/plugin can only handle its own button states.
To make something like this work, I'd have to find another way. Maybe introduce another flag like the dirty flag which only makes the button left enabled.

**Comment by wmjordan** [comment]
After some contemplation, I think that for my situation, there is no need to introduce another flag.
My plugin creates a new document, then clears the dirty flag. What is different from a "clean" document from the file system is that the generated document **does not have a file path.**
Thus, the Save button can check whether the document has a file path, if no, it is enabled, otherwise, it does what it does nowadays.

**Comment by wmjordan** [comment]
Thank you for having this implemented. I am feeling good with the new version.
