### ISSUE TITLE
No File Tree Upon Start

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#297]
Attached Please find GIF demonstrates no previous file or File Tree Upon Start Thank You Kindly
![No File Tree Upon Start](https://user-images.githubusercontent.com/48535920/211076429-be2c0260-9edc-4de1-8d24-5efbbc51e450.gif)

**Comment by stefankueng** [comment]
when opening with no file, the file tree is empty because there's no path to show the tree for.
Do you have a suggestion on what path the tree should show in this case?
Or maybe show an info text instead of a completely empty tree? Maybe "file tree empty - current tab has no path"
Other suggestions?

**Comment by PaltryProgrammer** [comment]
Please note in GIF provided the tree and previous file disappeared upon reopen . This never happened until recently . Prior upon reopen the previously open files and tree were reloaded . Thank You Kindly

**Comment by stefankueng** [comment]
to reopen files when BP starts you have to enable this. In the gif it seems that you don't have this enabled.
File section in the ribbon (leftmost section), the button right of the "save" button.

**Comment by PaltryProgrammer** [comment]
Thank You Kindly I don't recall pressing this button in past. I assumed reload was automatic/default. Thank You Again
