### ISSUE TITLE
Component Pascal lexer for BowPad

### ISSUE THREAD

**Issue by 1997tn** [stefankueng/BowPad#307]
I think the cause for https://github.com/stefankueng/BowPad/issues/306 is because there is no lexer for Component Pascal (I have to use Modula lexer) so when it encountered Component Pascal specific constructs it failed to parse them and it started to freeze.

**Comment by 1997tn** [comment]
@stefankueng Your commit is wrong. Even though the language's name has Pascal in it, the fact is it's an Oberon dialect and has nothing to do with Pascal. I wrote it very clear here: https://github.com/ScintillaOrg/lexilla/issues/127 If you really want to add Component Pascal now and not waiting for upstream to add a Component Pascal lexer, I think you should add it to Modula lexer.

**Comment by stefankueng** [comment]
again: what exactly is colored wrong?
please give an example:

- What did you expect to happen/show
- What happened/showed instead

**Comment by 1997tn** [comment]
> again: what exactly is colored wrong? please give an example:
> 
> * What did you expect to happen/show
> * What happened/showed instead

The file Form.cp crashed BowPad as I reported, you said you can't reproduce but it's a real problem for me. Maybe because I'm using Windows 7. I think the reason it crashed because there is no Component Pascal lexer so it failed to parse Component Pascal source file, so I asked for a Component Pascal lexer. If you are so sure my report about Form.cp crashed BowPad is not reproducible then please just close this issue together with that issue. But, revert the commit, Component Pascal has nothing to do with the language Pascal, grouping it this way is wrong.

**Comment by stefankueng** [comment]
the problem with the crash is in the lexilla lexer. I linked to the issue I created there from that issue you opened. #306 

This issue is about a pascal lexer. I added styling using the pascal lexer in this issue.
Then you said that my commit is wrong and I should revert it.

Did you even look at my commit? If so, do you understand it? If not then don't say it's wrong without any further comment or explanation about what exactly is wrong with it.

Because there's no "grouping" done here. And what are you talking about "Component Pascal" has nothing to do with the language Pascal? What "Component Pascal"?

**Comment by 1997tn** [comment]
> the problem with the crash is in the lexilla lexer. I linked to the issue I created there from that issue you opened. #306
> 
> This issue is about a pascal lexer. I added styling using the pascal lexer in this issue. Then you said that my commit is wrong and I should revert it.
> 
> Did you even look at my commit? If so, do you understand it? If not then don't say it's wrong without any further comment or explanation about what exactly is wrong with it.
> 
> Because there's no "grouping" done here. And what are you talking about "Component Pascal" has nothing to do with the language Pascal? What "Component Pascal"?

I did read your commit and I understand it. I see you added .cp extension as Pascal source. This is wrong. What is Component Pascal? An Oberon dialect wanted to gain more market by using the trick to put Pascal in it name!

See: https://en.wikipedia.org/wiki/Component_Pascal :smile:

**Comment by stefankueng** [comment]
Well, I added cp as an extension because that's the extension of the file you first reported a problem with, mentioning that while **it was Pascal** you had to use the Modula lexer for it instead.

Also, I think you don't understand the concept of a lexer: a lexer is used to style/color files accordingly. A lexer does not understand the syntax itself. For example the cpp lexer is used not just for cpluslus but also for c,c#,java, and a few other languages as well. Because it doesn't matter what language it is exactly, it only matters that the coloring is good enough.

**Comment by 1997tn** [comment]
> Well, I added cp as an extension because that's the extension of the file you first reported a problem with, mentioning that while **it was Pascal** you had to use the Modula lexer for it instead.
> 
> Also, I think you don't understand the concept of a lexer: a lexer is used to style/color files accordingly. A lexer does not understand the syntax itself. For example the cpp lexer is used not just for cpluslus but also for c,c#,java, and a few other languages as well. Because it doesn't matter what language it is exactly, it only matters that the coloring is good enough.

You should add .cp as Modula source file than Pascal source file. This is what I wanted to tell you.
