### ISSUE TITLE
Ctrl+End was very slow in word-wrapped big files

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#32]
It seems that it is related to issue #25 due to the word-wrapping.

**Comment by stefankueng** [comment]
Word-wrapping actually is slow by itself.
For big files, Scintilla does word-wrapping only up to the point of the last visible line.
So if you hit Ctrl+End then Scintilla has to calculate the line widths of the whole file in one go, and that's what is so slow.
Nothing I can do in BP here, since it's Scintilla code only that causes the slowdown.
