### ISSUE TITLE
Feature Request : Display File Tree Folder Path

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#335]
greetings kind regards this is to request feature i.e. display of File Tree Folder Path which i could not locate in current version thank you kindly please see attached PNGs re/ same demonstrate lack of said display and of version utilized . please note the path at top of application window i assume is of current file which of course may be outside of Tree Folder Path . thank you again
![image](https://github.com/stefankueng/BowPad/assets/48535920/434e8931-d845-4f4a-9f5e-00d202bfce70)
![image](https://github.com/stefankueng/BowPad/assets/48535920/190270ff-4e7c-4ce1-b8f1-07c16e655f65)

**Comment by PaltryProgrammer** [comment]
Witam, czy jesteś pewien, że to mój post, na który chcesz odpowiedzieć? Mój post nie dotyczy błędów w tłumaczeniu. Wszystkiego najlepszego.

**Comment by stefankueng** [comment]
the current file is always shown in the tree view. maybe not directly but inside a subfolder.

showing a full path at the top of the tree view is not really an option since it would be too long and clippee, or shown shortened which makes it less useful.

I'm going with tooltips showing the full paths when you hover over the files in the tree view. I hope that's ok.

**Comment by PaltryProgrammer** [comment]
super thank you
