### ISSUE TITLE
Click the right scrollbar to pagdown/up the page

### ISSUE THREAD

**Issue by caoguosong** [stefankueng/BowPad#364]
I want pagdown/up then page, when the I click the right scrollbar.

And what should I do ?

Thanks a lot.

**Comment by stefankueng** [comment]
the right scroll bar works in so called map mode by default. That's by design.
If you really, really, really want the scrollbar to do pageup/down on click, you have to edit the `settings `file (located in `%appdata%\BowPad` (for installed version) or the folder where the bowpad.exe is for portable versions.
find the `[View]` section, add:
`scrollstyle = 0`
then restart Bowpad

**Comment by caoguosong** [comment]
Thanks a lots !
