### ISSUE TITLE
Style configuration not working

### ISSUE THREAD

**Issue by stefankueng** [stefankueng/BowPad#387]
I tried again today the Style Configurator issue, and took a video. I just can't get it to work.
Changes are randomly lost. I usually set all languages with reserved keywords in blue, variables in dark red,
properties in dark blue, comments in green, and function names (suffixed by parentheses) in red,
among other colors. It helps me focus with consistency while working on any language. I tried both
PowerShell and C# to no avail, but I was able to make changes to AutoHotkey.

(mentioned in #376)

**Comment by stefankueng** [comment]
Also: add a button to reset the style to the default.

**Comment by mdnava** [comment]
Hi @stefankueng 

Sorry for not creating a new issue, I did think about it, just didn't do it in case those were issues
caused by myself missing something. I did miss the encoding option, and the "about".

I attach the config files, (style customizations just randomly disappear):

[BowPadConfig.zip](https://github.com/user-attachments/files/16482381/BowPadConfig.zip)

I also attach the full BowPad folder so it would be easier to reproduce:
(I'll remove this later on)

[BowPadFullFolder.zip](https://github.com/user-attachments/files/16482419/BowPadFullFolder.zip)

Here's also the video of the Style Configurator, so it rests on its own issue:

https://github.com/user-attachments/assets/1afbc0dd-8532-4f75-bbb1-b22553fcf26c

Have a nice day!
