### ISSUE TITLE
lexer for log files

### ISSUE THREAD

**Issue by stefankueng** [stefankueng/BowPad#95]

**Comment by wmjordan** [comment]
Hi,

is it possible to disable the lexer for log files?

I found it obviously slowed down the speed when I opened log files with BowPad.
Before the upgrade, it took BowPad less than 1 second to open a small log file on my server with about 150000 lines, and after applying the recent version, it costed at least 6 seconds. The more terrible experience was that the slow-down not only occurred while opening a file, but also when I switch tabs between log files! :(

**Comment by wmjordan** [comment]
Since log files are usually huge (150000 lines in my previous situation are small ones) and they might be written line by line in most cases (I have gotten multiple line log entries, but I don't care about improper syntax highlight).

I guess you don't have to do parse against the whole file or the suggested range by Scintilla. Just parse those lines visible on the screen may help improve the performance significantly.

**Comment by stefankueng** [comment]
yes: configure for *.log files the text lexer

**Comment by wmjordan** [comment]
Thank you for looking into the problem.

Now it performed in about 3 seconds when opening aforementioned log file. A bit better, but still slow. For a file with 250000 lines, it took about 7 seconds to open.

For log files, most items are of single line. I think there's no need to provide Folding.
I recompiled the source code by commenting all lines inside the `Fold` function, and the open speed was about 2 seconds then.

However, for ordinary txt files, it took less than 1 second. It seems that the syntax highlight part of the log lexer still has some margin for optimization.

**Comment by wmjordan** [comment]
I recompiled the source code with your recent modification.
I found that it was still slow when opening log files.
Hence I debugged the lexer.

I found that on opening the document, `startPos` = 0 and `length` = **document_length** will be pasted to the lex function.
Since log files are usually large, parsing the whole document will take quite considerable time, which is not so efficient.

And maybe we can make an assumption that lines in log files seldom have relations between each other and parse only visible part of the file and forget invisible parts?

**Comment by stefankueng** [comment]
I figured out why always the whole document gets styled. I'll make some changes to avoid that. Push coming soon.

**Comment by stefankueng** [comment]
Push done. Now it should be very fast

**Comment by wmjordan** [comment]
Great! Much better now. I can keep using this lexer eventually.

Is it possible to customize this lexer?

For instance, I prefer tagging the following things:
`[Info]` uses INFODEFAULT
`[Warn]` and `[Debug]` use WARNBLOCK
`[Error]` uses ERRORBLOCK

Perhaps making them case sensitive can better boost the performance since log files are generated by programs with arbitrary formats.

My log files have a lot of numbers, device serial numbers, hex codes, IP addresses and port numbers, time stamps, thus I prefer numeric styles to be turned off otherwise I will see a lot of blue characters around the file.

Is it possible to configure log keywords and style pairs and toggling numeric styles? A configuration file with some comments like customizing the shortcuts may be viable implementation for IT Pros.

**Comment by stefankueng** [comment]
with the last commit, you could configure your own mark-words. You could write your own bplex config file:
https://tools.stefankueng.com/BowPad_lexerconfig.html
just look at the properties.ini file, you can copy just the relevant parts for the log lexer to your bplex file.

but if you just want to configure the colors: use the "configure styles" button on the ribbon.

**Comment by wmjordan** [comment]
Thank you for the information and the new commit.

I tried to download the template file from your web page from the "First, get the template for a custom lexer styling from _here_." link. However, a 404 error occurred. I found an extra dot before "template" in the link "https://tools.stefankueng.com/.template.bplex". Please remove that dot in your page.

I am sorry that I could not figure out how to write a bplex file to override the existing lexer for the "log" file.
Could you take the trouble of writing such a file as an example for me?

**Comment by stefankueng** [comment]
here's a bplex file for the log lexer (will overwrite the BP config).
[log.zip](https://github.com/stefankueng/BowPad/files/5476780/log.zip)

**Comment by wmjordan** [comment]
Thank you for the file.
I checked the `prop_*strings` to the following, but it seemed that `[Warn]`, `[Debug]` was not working and `[Info]` might not be doing its job, only `[Error]` could change the line style to `ERRORBLOCK`.

````ini
Prop_debugstrings=[Debug]
Prop_infostrings=[Info]
Prop_warnstring=[Warn]
Prop_errorstrings=[Error]
```

**Comment by stefankueng** [comment]
made some fixes.
But you also have to change `Prop_warnstring=` to `Prop_warnstrings=` in the bplex file

**Comment by wmjordan** [comment]
Thank you for the update.
It is working as expected now.

**Comment by wmjordan** [comment]
Recently I tried to configure the syntax color for the ERRORNUMBER, ERRORBLOCK, etc.

I changed the foreground color of ERRORBLOCK, then the foreground color of ERRORNUMBER. While the colors were changing BowPad immediately changed the rendered result in the document window. I was finally satisfied with some colors. Then clicked the Ok button.

After that, the **background color** of the above two items were unexpectedly changed to white.
Please see whether this issue is reproducable on your machine.

**Comment by stefankueng** [comment]
you mean you used the "configure styles" dialog?

**Comment by stefankueng** [comment]
can't reproduce that, sorry.
Anything special about what/how you did it?

**Comment by wmjordan** [comment]
I customized the property of error strings to `[Error]` for `Prop_errorstrings` the log lexer.
It should not be the difference.

The extract procedure is listed below:

1. Make sure that no item about the log lexer is in the userconfig
2. Open a log file and bring out the _configure styles_ dialog
3. Click the `[Error]` string in the document window to configure it

<img width="512" alt="shot" src="https://user-images.githubusercontent.com/12182730/98311401-44257780-200a-11eb-837b-1989be8f20a4.PNG">

4. Click the foreground color to change its color

<img width="510" alt="shot" src="https://user-images.githubusercontent.com/12182730/98311437-5e5f5580-200a-11eb-94ab-b3d024e3dd05.PNG">

5. Click the Ok button to close the _configure styles_ dialog.
6. The background color will be unexpectedly changed to white.

<img width="270" alt="shot" src="https://user-images.githubusercontent.com/12182730/98311523-8f3f8a80-200a-11eb-885c-fdfca1c64231.PNG">
